apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  POSTGRES_HOST: postgres  # Altere para o IP do seu host Docker se necessário
  POSTGRES_USER: ps_user
  POSTGRES_DB: ps_db
  POSTGRES_PORT: "5432"