"""Adding the Roles model schema migration

Revision ID: fa6c105ff4f5
Revises: f702703b181a
Create Date: 2025-02-03 01:38:52.066097

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fa6c105ff4f5"
down_revision: Union[str, None] = "f702703b181a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_tenant_name"),
    )
    op.create_unique_constraint("TenantUniqueConstraintName", "tenants", ["name"])
    op.create_unique_constraint("TenantUniqueConstraintId", "tenants", ["id"])
    op.create_unique_constraint("TenantUniqueConstraintSlug", "tenants", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("TenantUniqueConstraintName", "tenants", type_="unique")
    op.drop_constraint("TenantUniqueConstraintId", "tenants", type_="unique")
    op.drop_constraint("TenantUniqueConstraintSlug", "tenants", type_="unique")
    op.drop_table("roles")
    # ### end Alembic commands ###
