"""Adding the Database model schema migration

Revision ID: c548b99cf55c
Revises: fa6c105ff4f5
Create Date: 2025-02-03 18:53:03.880848

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c548b99cf55c"
down_revision: Union[str, None] = "fa6c105ff4f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "databases",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "db_type",
            sa.Enum("MYSQL", "POSTGRES", "REDIS", "SQLSERVER", "MONGO", "MARIA", name="databasetype"),
            nullable=False,
        ),
        sa.Column("connection_string", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_string"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint("RoleIdConstraint", "roles", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("RoleIdConstraint", "roles", type_="unique")
    op.drop_table("databases")
    op.execute("DROP TYPE databasetype")
    # ### end Alembic commands ###
