"""Adding the Database History model schema migration

Revision ID: fd4c995e4555
Revises: fb41d5a1229e
Create Date: 2025-02-03 19:38:52.465870

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fd4c995e4555"
down_revision: Union[str, None] = "fb41d5a1229e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("schemas", sa.String(), nullable=True),
        sa.Column("database_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["database_id"],
            ["databases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint("DatabaseIdConstraint", "databases", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("DatabaseIdConstraint", "databases", type_="unique")
    op.drop_table("history")
    # ### end Alembic commands ###
