name: Develop-Pipeline
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      IS_PROD: "true"
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      TEST_DATABASE_URL: "postgresql+asyncpg://app_user:app_password@localhost:5433/app_db"
      DATABASE_URL: "postgresql+asyncpg://app_user:app_password@localhost:5433/app_db"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: app_db
          POSTGRES_PASSWORD: app_password
          POSTGRES_USER: app_user
        ports:
          - 5433:5432

    steps:
      - name: Cloning the Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.1"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run task test
